image: node:alpine

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - dist
    when: on_success

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv public .public
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master